### PR TITLE
Setup stickler

### PR DESCRIPTION
**Pull request by keshav-c**
The code is in the feature branch `library-project` and is deployed from the `gh-pages` branch. Please note that, I have had to do the project alone. I have been given permission from student success to do so. Also note that, I have started this project some days earlier. The linter setup procedure has changed since then. I have setup eslint as per requirements, but at the time there were no instructions about putting `node_modules` in gitignore.

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Nice work on this project, but the following changes need to be done before moving on ⬇️** 

* [ ] There is an array to store the instances of `Book` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library)).

- ##### `addBookToLibrary` function ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/book_array_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library)), 

* [ ] The application has a `addBookToLibrary` function
* [ ] It can take user's input
* [ ] It stores the new Book objects into an array

##### `New Book` button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

* [ ] It has a `New Book` button
* [ ] It brings up a form
  * [ ] The form has an `author` field
  * [ ] The form has a `title` field
  * [ ] The form has a `number of pages` field
  * [ ] The form allows to mark the `Book` status as `read`

##### Display `Book`

* [ ] It has a `render` function ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/render_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
* [ ] It displays on the page every book contained in the array ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/render_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
* [ ] Each `Book` displayed has a `button` to `remove` the `Book` from the `Library` array ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/remove_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
* [ ] Each `Book` displayed has a `button` to `toggle` the `Book` read status ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/toggle_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

* [ ] Node modules - .lock files should be in the repository to avoid problems with future versions of the dependencies. It also helps to keep the same versions in different installations of the app (production, development, etc...) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/lock_files_requirement.png) from Pathwright)

- You have implemented most of the above but try to separate them into functions like it's required rather than writing everything inside the eventListener.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by keshav-c** [comment]
* [x] There is an array to store the instances of `Book` 
##### `addBookToLibrary` function 
* [x] The application has a `addBookToLibrary` function
* [x] It can take user's input
* [x] It stores the new Book objects into an array

##### `New Book` button 

* [x] It has a `New Book` button
* [x] It brings up a form
  * [x] The form has an `author` field
  * [x] The form has a `title` field
  * [x] The form has a `number of pages` field
  * [x] The form allows to mark the `Book` status as `read`

##### Display `Book`

* [x] It has a `render` function
* [x] It displays on the page every book contained in the array
* [x] Each `Book` displayed has a `button` to `remove` the `Book` from the `Library` array 
* [x] Each `Book` displayed has a `button` to `toggle` the `Book` read status

* [x] Node modules - .lock files should be in the repository to avoid problems with future versions of the dependencies. It also helps to keep the same versions in different installations of the app (production, development, etc...) 

## Fixes

As mentioned in the review, all the requirements listed were already fulfilled. [This commit](https://github.com/keshav-c/js-library/commit/c5e3343bcdfba76f9e0b0bb2145343d098521945)
- Moved the code to add new book to a function called `addBookToLibrary` which is called from the event listener for the form.
- Changed the name of the `renderList` function which displays all the books stored in the _array_ to `render`.

**Review by bellom — APPROVED** [review]
## Hi @keshav-c :clap: 

**Great work making all the necessary corrections from the previous review.**

#### NOTE: In your next project;
1. Let's separate the DOM from application logic, you can create another file for DOM.

image

2. Update your `README` file and remove unnecessary content
Checkout out the below link for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59623451/

3. Node modules should be ignored as it makes it impossible to leave a proper review addressing your code, and commenting there, makes the review process longer than it should so that should be added to the gitignore fil.

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by keshav-c** [comment]
:+1:

**Pull request merged**
